export const PRODUCTS_ADD_PRODUCT = "ADD_PRODUCT"
export const PRODUCTS_EDIT_PRODUCT = "EDIT_PRODUCT";
export const PRODUCTS_DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCTS_GET_PRODUCTS= "GET_PRODUCTS";